### ISSUE TITLE
why bother with the approximation method?

### ISSUE THREAD

**Issue by rmflight** [mingzehuang/latentcor#7]
In the documentation, it is stated that the approximation method makes it faster. No timing examples are provided, however, nor even a statement of how a user is actually going to benefit.

**Comment by irinagain** [comment]
The approximation method has been originally proposed in Yoon et al. 2021 JCGS paper that can be accessed [here](https://doi.org/10.1080/10618600.2021.1882468) for continuous/binary/truncated variable types (no ternary case allowed). The timing examples are also provided in that paper, although it does not use `latentcor` package as it has been developed only later. In fact, `latentcor` implementation of approximation method is inspired by this paper's proposal, `latentcor` additionally has a ternary case and a more clever choice of grid for all cases to save memory footprint. In practice, the realized amount of speed up depends on 
 1. The chosen tolerance for `optimize` function (parameter `tol`) used when `method = "original"`. The smaller is the tolerance, the higher is the accuracy, the slower is the method. The default in latentcor is 1e-8 (correlation is estimated with precision up to 8 decimal places). 
 2. The types of variables between which the correlation is computed. The example in Yoon et al. 2021 Table 1 shows roughly 7 fold speed up on binary/continuous case, and 50 fold speed up on truncated/truncated case.
 3. The chosen value for parameter `ratio` which controls the region of values over which the interpolation is performed. The larger is the `ratio`, the larger is the region, and so more values will be calculate by interpolation rather than numerical inversion (hence speed-up). 
 4. The total number of variables because each correlation value has to be computed separately for each pair of variables.

With small datasets like mtcars (11 variables, 30 samples), which method is used doesn't matter very much. While approximation method is still faster here, the time for original method is not unreasonable:
```r
types = c("con", "ter", "con", "con", "con", "con", "con", "bin", "bin", "ter", "con")
microbenchmark(latentcor(mtcars, types = types, method = "original"),
               latentcor(mtcars, types = types, method = "approx"))
# Unit: milliseconds
#  min       lq        mean      median        uq      max    neval
#  201.9872 215.6438   225.30385 221.5364 226.58330 411.4940   100
#   71.8457  75.1681   82.42531  80.1688  84.77845 238.3793    100
# This is run on Windows 10 with Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz   3.20 GHz
```
With high-dimensional datasets, however, like the American Gut Project data considered as an example in Yoon et al., 2021 with 491 variables, 6482 samples and all variables being truncated, the difference is 5 minutes versus 1 hour for one time calculation, and the latter makes the use of original method with subsampling or bootstrapping on these data computationally prohibitive.

We will add more details to vignette and documentation, but hopefully this adds more clarity for now.

**Comment by rmflight** [comment]
All that is great. However, if you make a speed claim, there should be an example that demonstrates the need for a faster method.

Therefore, I am simply asking that there is an example in the README or vignette that demonstrates that the approximation method offers a speed improvement with minimal hit to accuracy.

**Comment by rmflight** [comment]
These issues are all related to the review criteria for JOSS, where if a performance claim is made, then there needs to be an actual way to check that there is a real difference in performance.

**Comment by mingzehuang** [comment]
Thank you for your suggestion! We've add speed comparison for both examples in README.md. We also add speed comparison for the example in section `Approximation method (method = "approx")` to see the speed difference, together with approximate errors which we've already put there.
Let us know if any more example/illustration needed. Thank you again!

**Comment by mingzehuang** [comment]
In the math vignette "latentcor_math", we just added a section `Speed Comparison` under `Approximation method (method = "approx")` with performance claim and log-log plot for different dimensions.
Let us know if any more need to be added. Thanks!

**Comment by mingzehuang** [comment]
[latentcor_math](https://mingzehuang.github.io/latentcor/articles/latentcor_math.html)

**Comment by rmflight** [comment]
This is awesome! Thank you!
